version: '3'
services:
  elasticsearch1:
    image: elasticsearch:5.2.0
    container_name: elasticsearch1
    environment:
     - cluster.name=pixerapp-es
     - node.name=elasticsearch1
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms350m -Xmx350m"
    ulimits:
     memlock:
      soft: -1
      hard: -1
     nofile:
      soft: 65536
      hard: 65536
    cap_add:
     - IPC_LOCK
    networks:
     - esnet
    volumes:
     - /root/es/config:/usr/share/elasticsearch/config
     - esdata1:/usr/share/elasticsearch/data
  haproxy:
    image: pixerapp/haproxy:1.2.2-haproxy-1.7.2
    environment:
     - DNS_TCP_ADDR=127.0.0.11
     - DNS_TCP_PORT=53
     - FLOATING_IP=*
     - STATSAUTH=admin:password
    networks:
     - esnet
    ports:
     - 80:80
     - 443:443
    volumes:
     - /etc/ssl/pixerapp.com/:/etc/ssl/pixerapp.com
     - /root/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
  esnet:
    driver: bridge

volumes:
  esdata1:
    driver: local
